# Generated by Django 4.0.3 on 2022-05-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_category_size_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.productitem'),
            preserve_default=False,
        ),
    ]
