# Generated by Django 4.0.3 on 2022-05-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_productitem_options_remove_productitem_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.size'),
        ),
    ]
