# Generated by Django 4.0.3 on 2022-05-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cart_size_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['state', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created_date', 'ordering': ['state', 'name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='archived_sizes',
        ),
    ]
