# Generated by Django 4.0.3 on 2022-05-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='sign',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='present',
            name='state',
            field=models.CharField(choices=[('SN', 'Sent'), ('RD', 'Read')], db_index=True, default='SN', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='productitem',
            unique_together={('product_id', 'color')},
        ),
    ]
