# Generated by Django 4.0.3 on 2022-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_present_sign_alter_present_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='ucoin_count',
            field=models.IntegerField(default=0),
        ),
    ]
