# Generated by Django 4.0.3 on 2022-05-25 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_userinfo_patronymic_alter_userinfo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
