# Generated by Django 4.0.3 on 2022-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_present_user_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_photo',
            field=models.ImageField(upload_to='storage/images/defaultProductPhotos/'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='photo',
            field=models.ImageField(upload_to='storage/images/productItemPhotos/'),
        ),
    ]
