# Generated by Django 4.0.3 on 2022-06-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_product_default_photo_alter_productitem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ava_back_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ava_main_color',
            field=models.CharField(default='#FDB4FF', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_photo',
            field=models.ImageField(upload_to='defaultProductPhotos/'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='photo',
            field=models.ImageField(upload_to='productItemPhotos/'),
        ),
    ]
