# Generated by Django 4.0.3 on 2022-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_product_category_id_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_photo',
            field=models.ImageField(upload_to='images/defaultProductPhotos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('Archived', 'Archived'), ('Actual', 'Actual')], db_index=True, default='Archived', max_length=50),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='photo',
            field=models.ImageField(upload_to='images/productItemPhotos/'),
        ),
    ]
