# Generated by Django 4.0.3 on 2022-07-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_customer_product_have_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'Цвет товара', 'verbose_name_plural': 'Цвета товаров'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_photo',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ava_back_color',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ava_main_color',
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('photo', models.ImageField(upload_to='images/productItemPhotos/')),
                ('main_photo', models.BooleanField(default=False)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productitem')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товаров',
                'ordering': ['main_photo'],
            },
        ),
    ]
