# Generated by Django 4.0.3 on 2022-07-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(db_index=True, default='чёрн', max_length=30),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='api.size'),
        ),
    ]
