# Generated by Django 4.0.3 on 2022-07-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_productitem_color_alter_productitem_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='api.size'),
        ),
    ]
