# Generated by Django 4.0.3 on 2022-07-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_productitem_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['-main_photo'], 'verbose_name': 'Фотография товара', 'verbose_name_plural': 'Фотографии товаров'},
        ),
    ]
