# Generated by Django 4.0.3 on 2022-07-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_productphoto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size_id',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.size'),
        ),
    ]
